Repository entando/entando-plugin-jpcontentscheduler, pull requests merged in 2020-07, with the labels that each got.

#2 ENG-827 preparing for first PR
  README.md
  charts/entando-plugin-jpcontentscheduler/.helmignore
  charts/entando-plugin-jpcontentscheduler/Chart.yaml
  charts/entando-plugin-jpcontentscheduler/Makefile
  charts/entando-plugin-jpcontentscheduler/README.md
  charts/entando-plugin-jpcontentscheduler/templates/NOTES.txt
  charts/entando-plugin-jpcontentscheduler/templates/_helpers.tpl
  charts/entando-plugin-jpcontentscheduler/templates/canary.yaml
  charts/entando-plugin-jpcontentscheduler/templates/deployment.yaml
  charts/entando-plugin-jpcontentscheduler/templates/hpa.yaml
  charts/entando-plugin-jpcontentscheduler/templates/ingress.yaml
  charts/entando-plugin-jpcontentscheduler/templates/ksvc.yaml
  charts/entando-plugin-jpcontentscheduler/templates/service.yaml
  charts/entando-plugin-jpcontentscheduler/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  jenkins-x.yml
  pom.xml
Labels: size/XL

#3 ENG-877: Add LICENSE file
  LICENSE
Labels: size/L

#6 ENG-942 Paul's ENG label fixes
  src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/config/package_en.properties
  src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/global-messages_en.properties
Labels: size/M

#7 ENG-936 Amend content scheduler menu label
  src/main/java/org/entando/entando/plugins/jpcontentscheduler/apsadmin/global-messages_en.properties
Labels: size/XS

#8 ENG-950 removed admin-console war dependency
  OWNERS
  OWNERS_ALIASES
  pom.xml
  src/test/config/conf/systemParams.properties
Labels: size/L
